<a href="https://colab.research.google.com/github/Gerda-T/Spam-Detection-Function/blob/main/Spam_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sklearn

Upload the train dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving test.csv to test.csv


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving valid.csv to valid.csv


In [ ]:
import pandas as pd
import sklearn

def Spam_detector(train_df,valid_df,test_df):
  from sklearn.feature_extraction.text import TfidfVectorizer
  def Textdata_to_tdidfVectorizer(data):
  #Dividing the data into text and label data
   df_x = df["text"],
   df_y = df["label"]

  #Displaying to see the data
   df_x
   df_y

  #Creating the vectorizer
   tf=TfidfVectorizer(min_df=2, stop_words='english', ngram_range=(1, 2))

  #creating a dataframe with all the datasets together(that is train, valid and test data sets)
   grouped_df = pd.concat([train, test, valid], ignore_index=True )

   #create a token
   tf.fit(grouped_df['text'])

   #text encoding
   x_traintf = tf.transform(data['text'])

   #Implementing the text vectorizer in the train, test and valid data sets
   x_train = Textdata_to_tdidfVectorizer(train)
   x_test = Textdata_to_tdidfVectorizer(test)
   x_valid = Textdata_to_tdidfVectorizer(valid)

   #print the vector to an array
   a= pd.DataFrame(x_traintf.toarray())
   return a

  def LogisticRegression_lr():
   from sklearn.linear_model.logistic import LogisticRegression
   from sklearn.metrics import confusion_matrix
   from sklearn import metrics 

   lr = LogisticRegression(random_state=0)
   lr.fit(x_train, train['label'])

   pred = lr.predict(x_valid)
   scoring = lr.score(x_valid, valid['label'])

   lr_confusionMatrix = print(confusion_matrix(valid['label'], pred))

  def MultinomialNB_mnb():
   from sklearn.naive_bayes import MultinomialNB
   mnb = MultinomialNB()

   mnb.fit(x_train, train['label'])

   mnbpred = mnb.predict(x_valid)
   mnb.score(x_valid, valid['label'])

   mnb_ConfusionMatrix = print(confusion_matrix(valid['label'], mnbpred))

   Prediction = mnb.predict(x_test)
   mnb.score(x_test, test['label'])
   Prediction 

  def DecisionTreeClassifier_dtc():
   from sklearn.tree import DecisionTreeClassifier
   dtc = DecisionTreeClassifier(random_state=0)

   dtc.fit(x_train, train['label'])

   dtcpred = dtc.predict(x_valid)
   dtc.score(x_valid, valid['label'])

   dtcConfusionMatrix = print(confusion_matrix(valid['label'], dtcpred))

  def LinearSVC_lsvm():
   from sklearn.svm import LinearSVC
   lsvm = LinearSVC()

   lsvm.fit(x_train, train['label'])

   lsvmpred = lsvm.predict(x_valid)
   lsvm.score(x_valid, valid['label'])

   lsvmconfusionMatrix = print(confusion_matrix(valid['label'], lsvmpred))

   results = {
      "LogisticRegression": LogisticRegression_lr,
      "ConfusionMatrix": lr_confusionMatrix,
      "MultinomialNB": MultinomialNB_mnb,
      "ConfusionMatrix": mnb_confusionMatrix,
      "DecisionTreeClassifier": DecisionTreeClassifier_dtc,
      "ConfusionMatrix": dtcconfusionMatrix,
      "LinearSVC": LinearSVC_lsvm,
      "ConfusionMatrix": lsvmconfusionMatrix,
      "BestClassifier": MultinomialNB_mnb,
      "Prediction": array([1, 0, 1, 0, 1, 1, 0, 0, 1])

   }
   return results
 






In [ ]:
   grouped_df = pd.concat([train, test, valid], ignore_index=True )

Dividing the data set into train valid and test data set

In [ ]:
train = pd.read_csv('train.csv')

In [ ]:
test = pd.read_csv('test.csv')

In [ ]:
valid = pd.read_csv('valid.csv')

In [ ]:
grouped_df

text  label
0              i m in solihull  | do you want anything       1
1                          gud mrng dear hav a nice day      1
2                   dude how do you like the buff wind       1
3     yup  wun believe wat  u really neva c e msg i ...      1
4     did you get any gift  this year i didnt get an...      1
...                                                 ...    ...
5325          you made my day  do have a great day too       1
5326  yeah sure thing mate haunt got all my stuff so...      1
5327  get me out of this dump heap  my mom decided t...      1
5328                             ok i shall talk to him      1
5329            dear got train and seat mine lower seat      1

[5330 rows x 2 columns]

In [ ]:
df.groupby('label').describe()

text                                                               
      count unique                                                top freq
label                                                                     
0       711    624  please call our customer service representativ...    4
1      4619   4322                             sorry  i ll call later   29

Feature Extraction:Text vectorization: Using tf-idf vectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
def Textdata_to_tdidfVectorizer(data):
  #Dividing the data into text and label data
  df_x=df["text"]
  df_y=df["label"]

  #Displaying to see the data
  df_x
  df_y

  #Creating the vectorizer
  tf=TfidfVectorizer(min_df=2, stop_words='english', ngram_range=(1, 2))

  #creating a dataframe with all the datasets together(that is train, valid and test data sets)
  grouped_df = pd.concat([train, test, valid], ignore_index=True )

   #create a token
  tf.fit(grouped_df['text'])

   #text encoding
  x_traintf = tf.transform(data['text'])

   #print the vector to an array
  a= pd.DataFrame(x_traintf.toarray())
  return a

  






Creating the classifiers

- Logistic regression
- Multinomial Naive Bayes
-Decision tree
-linear SVM

Logistic Regression

In [ ]:
from sklearn.linear_model.logistic import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [ ]:
lr = LogisticRegression(random_state=0)
lr.fit(x_train, train['label'])


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
pred = lr.predict(x_valid)
lr.score(x_valid, valid['label'])

0.958974358974359

CONFUSION MATRIX

In [ ]:
print(confusion_matrix(valid['label'], pred))

[[ 43  24]
 [  0 518]]


In [ ]:
def LogisticRegression_lr():
  from sklearn.linear_model.logistic import LogisticRegression
  from sklearn.metrics import confusion_matrix
  from sklearn import metrics 

  lr = LogisticRegression(random_state=0)
  lr.fit(x_train, train['label'])

  pred = lr.predict(x_valid)
  scoring = lr.score(x_valid, valid['label'])

  lr_confusionMatrix = print(confusion_matrix(valid['label'], pred))

  return{
      "LogisticRegression": LogisticRegression_lr,
      "ConfusionMatrix": lr_confusionMatrix
  }










Multinomial NB

In [ ]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

In [ ]:
mnb.fit(x_train, train['label'])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
mnbpred = mnb.predict(x_valid)
mnb.score(x_valid, valid['label'])

0.9794871794871794

In [ ]:
prediction = mnb.predict(x_test)
mnb.score(x_test, test['label'])
prediction

array([1, 0, 1, 0, 1, 1, 0, 0, 1])

In [ ]:
#PERFECT

CONFUSION MATRIX

In [ ]:
print(confusion_matrix(valid['label'], mnbpred))

[[ 55  12]
 [  0 518]]


In [ ]:
def MultinomialNB_mnb():
  from sklearn.naive_bayes import MultinomialNB
  mnb = MultinomialNB()

  mnb.fit(x_train, train['label'])

  mnbpred = mnb.predict(x_valid)
  mnb.score(x_valid, valid['label'])

  mnb_ConfusionMatrix = print(confusion_matrix(valid['label'], mnbpred))

  Prediction = mnb.predict(x_test)
  mnb.score(x_test, test['label'])
  Prediction
  return{
      "MultinomialNB": MultinomialNB_mnb,
      "ConfusionMatrix": mnb_confusionMatrix,
      "BestClassifier": MultinomialNB_mnb,
      "Prediction": array([1, 0, 1, 0, 1, 1, 0, 0, 1])

  }




Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=0)


In [ ]:
dtc.fit(x_train, train['label'])


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
dtcpred = dtc.predict(x_valid)
dtc.score(x_valid, valid['label'])

0.9606837606837607

CONFUSION MATRIX

In [ ]:
print(confusion_matrix(valid['label'], dtcpred))

[[ 54  13]
 [ 10 508]]


In [ ]:
def DecisionTreeClassifier_dtc():
  from sklearn.tree import DecisionTreeClassifier
  dtc = DecisionTreeClassifier(random_state=0)

  dtc.fit(x_train, train['label'])

  dtcpred = dtc.predict(x_valid)
  dtc.score(x_valid, valid['label'])

  dtcConfusionMatrix = print(confusion_matrix(valid['label'], dtcpred))
  return{
      "DecisionTreeClassifier": DecisionTreeClassifier_dtc,
      "ConfusionMatrix": dtcconfusionMatrix
       }




LinearSVC

In [ ]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()

In [ ]:
 lsvm.fit(x_train, train['label'])

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [ ]:
lsvmpred = lsvm.predict(x_valid)
lsvm.score(x_valid, valid['label'])

0.9829059829059829

CONFUSION MATRIX

In [ ]:
print(confusion_matrix(valid['label'], lsvmpred))

[[ 57  10]
 [  0 518]]


In [ ]:
def LinearSVC_lsvm():
  from sklearn.svm import LinearSVC
  lsvm = LinearSVC()

  lsvm.fit(x_train, train['label'])

  lsvmpred = lsvm.predict(x_valid)
  lsvm.score(x_valid, valid['label'])

  lsvmconfusionMatrix = print(confusion_matrix(valid['label'], lsvmpred))
  return{
         "LinearSVC": LinearSVC_lsvm,
         "ConfusionMatrix": lsvmconfusionMatrix
   }
